import { Inter } from "next/font/google";
import AuthContext from "./authContext";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
 {children, session}
) {
  return (
    <html lang="en">
      <AuthContext session={session}>
        <body className={inter.className}>{children}</body>
      </AuthContext>
    </html>
  );
}
